name: Compilar y Desplegar PDF
on: [push]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex # Cambia esto si tu archivo tiene otro nombre

      - name: Upload PDF to a branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages # El PDF se guardará en esta rama
          allow_empty_commit: true
          keep_files: false
          destination_dir: .
          # Solo incluimos el PDF en la rama de despliegue
          exclude_assets: '.github,*.tex,*.bib,*.cls,images'
